// This file contains the data for hero products displayed on the homepage.
export const products = [
  {
    id: "hy-push-pull-exhaust-fans",
    name: "HY-PUSH-PULL EXHAUST FANS",
    heroImage: "/product-images/hy-push-pull-exhaust-fans/hero.webp",
    images: ["/product-images/hy-push-pull-exhaust-fans/image-1.webp"],
    tags: ["featured", "hero"],
    category: "",
  },
  {
    id: "hy-cooling-pad",
    name: "HY COOLING PAD",
    heroImage: "/product-images/hy-cooling-pad/hero.png",
    images: ["/product-images/hy-cooling-pad/image-1.webp"],
    tags: ["featured", "hero"],
    category: "",
  },
  {
    id: "hy-silos",
    name: "HY SILOS",
    heroImage: "/product-images/hy-silos/hero.webp",
    images: ["/product-images/hy-silos/image-1.webp"],
    tags: ["featured", "hero"],
    category: "",
  },
  {
    id: "hy-electric-heaters",
    name: "HY-ELECTRIC HEATERS",
    heroImage: "/product-images/hy-electric-heaters/hero.webp",
    images: ["/product-images/hy-electric-heaters/image-1.webp"],
    tags: ["featured", "hero"],
    category: "",
  },
  {
    id: "hy-dry-and-wet-seprator",
    name: "HY-DRY AND WET SEPARATOR",
    heroImage: "/product-images/hy-dry-and-wet-seprator/hero.webp",
    images: ["/product-images/hy-dry-and-wet-seprator/image-1.webp"],
    tags: ["featured", "hero"],
    category: "",
  },
  {
    id: "hy-roof-ventilation-fan",
    name: "HY-ROOF VENTILATION FAN",
    heroImage: "/product-images/hy-roof-ventilation-fan/hero.webp",
    images: ["/product-images/hy-roof-ventilation-fan/image-1.webp"],
    tags: ["featured", "hero"],
    category: "",
  },
];
