export type Category =
   | "neagtive-pressure-fan"
   | "cooling-pad"
   | "farming-equipment"
   | "heating-equipment"
   | "fecal-cleaning-equipment"
   | "other-fans";

export const products = [
   {
      id: "hy-push-pull-exhaust-fans",
      name: "HY-PUSH-PULL EXHAUST FAN",
      heroImage: "/product-images/hy-push-pull-exhaust-fans/hero.webp",
      images: [
         "/product-images/hy-push-pull-exhaust-fans/image-2.jpg",
         "/product-images/hy-push-pull-exhaust-fans/image-1.webp",

         "/product-images/hy-push-pull-exhaust-fans/image-3.jpg",
      ],
      tags: ["featured", "hero"],
      category: "neagtive-pressure-fan",
      specifications: [
         {
            type: "HYFB-800",
            list: [
               { key: "Diameter blades (mm)", value: "710(29in)" },
               { key: "Frequency (Hz)", value: "50" },
               { key: "Motor rotational speed (r/min)", value: "≥1400" },
               { key: "Air flow (m³/h)", value: "26000" },
               { key: "Input power (W)", value: "370" },
               { key: "Noise decibels", value: "≤64" },
               { key: "Total pressure (Pa)", value: "60" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "800" },
               { key: "Width (mm)", value: "450" },
               { key: "Thickness (mm)", value: "450" },
            ],
         },
         {
            type: "HYFB-1000",
            list: [
               { key: "Diameter blades (mm)", value: "900(36in)" },
               { key: "Frequency (Hz)", value: "50" },
               { key: "Motor rotational speed (r/min)", value: "≥1400" },
               { key: "Air flow (m³/h)", value: "32000" },
               { key: "Input power (W)", value: "750" },
               { key: "Noise decibels", value: "≤64" },
               { key: "Total pressure (Pa)", value: "70" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1000" },
               { key: "Width (mm)", value: "450" },
               { key: "Thickness (mm)", value: "450" },
            ],
         },
         {
            type: "HYFB-1100",
            list: [
               { key: "Diameter blades (mm)", value: "1000(44in)" },
               { key: "Frequency (Hz)", value: "50" },
               { key: "Motor rotational speed (r/min)", value: "≥1400" },
               { key: "Air flow (m³/h)", value: "40000" },
               { key: "Input power (W)", value: "750" },
               { key: "Noise decibels", value: "≤64" },
               { key: "Total pressure (Pa)", value: "70" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1100" },
               { key: "Width (mm)", value: "450" },
               { key: "Thickness (mm)", value: "450" },
            ],
         },
         {
            type: "HYFB-1380",
            list: [
               { key: "Diameter blades (mm)", value: "1270(50in)" },
               { key: "Frequency (Hz)", value: "50" },
               { key: "Motor rotational speed (r/min)", value: "≥1400" },
               { key: "Air flow (m³/h)", value: "44800" },
               { key: "Input power (W)", value: "1100" },
               { key: "Noise decibels", value: "≤64" },
               { key: "Total pressure (Pa)", value: "56" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1380" },
               { key: "Width (mm)", value: "450" },
               { key: "Thickness (mm)", value: "450" },
            ],
         },
         {
            type: "HYFB-1530",
            list: [
               { key: "Diameter blades (mm)", value: "1400(56in)" },
               { key: "Frequency (Hz)", value: "50" },
               { key: "Motor rotational speed (r/min)", value: "≥1400" },
               { key: "Air flow (m³/h)", value: "58000" },
               { key: "Input power (W)", value: "1500" },
               { key: "Noise decibels", value: "≤64" },
               { key: "Total pressure (Pa)", value: "60" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1530" },
               { key: "Width (mm)", value: "450" },
               { key: "Thickness (mm)", value: "450" },
            ],
         },
      ],
   },
   {
      id: "hy-heavy-hammer-exhaust-fan",
      name: "HY-HEAVY HAMMER EXHAUST FAN",
      heroImage: "",
      images: [
         "/product-images/hy-heavy-hammer-exhaust-fan/image-1.webp",
         "/product-images/hy-heavy-hammer-exhaust-fan/image-2.webp",
      ],
      tags: [],
      category: "neagtive-pressure-fan",
      specifications: [
         {
            type: 'HYA480(18")',
            list: [
               { key: "Diameter blades (mm)", value: "410" },
               { key: "Blade rotational speed (r/min)", value: "1400" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "3600" },
               { key: "Total pressure (Pa)", value: "≤60" },
               { key: "Noise decibels", value: "≤60" },
               { key: "Input power (W)", value: "180" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "480" },
               { key: "Width (mm)", value: "320" },
               { key: "Thickness (mm)", value: "" },
            ],
         },
         {
            type: 'HYA-620(24")',
            list: [
               { key: "Diameter blades (mm)", value: "500" },
               { key: "Blade rotational speed (r/min)", value: "680" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "6500" },
               { key: "Total pressure (Pa)", value: "≤60" },
               { key: "Noise decibels", value: "≤60" },
               { key: "Input power (W)", value: "370" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "620" },
               { key: "Width (mm)", value: "620" },
               { key: "Thickness (mm)", value: "400" },
            ],
         },
         {
            type: 'HYA-800(29")',
            list: [
               { key: "Diameter blades (mm)", value: "710" },
               { key: "Blade rotational speed (r/min)", value: "660" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "22000" },
               { key: "Total pressure (Pa)", value: "≤60" },
               { key: "Noise decibels", value: "≤60" },
               { key: "Input power (W)", value: "370" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "800" },
               { key: "Width (mm)", value: "800" },
               { key: "Thickness (mm)", value: "400" },
            ],
         },
         {
            type: 'HYA-900(30")',
            list: [
               { key: "Diameter blades (mm)", value: "750" },
               { key: "Blade rotational speed (r/min)", value: "630" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "28000" },
               { key: "Total pressure (Pa)", value: "≤65" },
               { key: "Noise decibels", value: "≤65" },
               { key: "Input power (W)", value: "550" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "900" },
               { key: "Width (mm)", value: "900" },
               { key: "Thickness (mm)", value: "400" },
            ],
         },
         {
            type: 'HYA-1000(36")',
            list: [
               { key: "Diameter blades (mm)", value: "900" },
               { key: "Blade rotational speed (r/min)", value: "610" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "30000" },
               { key: "Total pressure (Pa)", value: "≤70" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "550" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1000" },
               { key: "Width (mm)", value: "1000" },
               { key: "Thickness (mm)", value: "400" },
            ],
         },
         {
            type: 'HYA-1100(40")',
            list: [
               { key: "Diameter blades (mm)", value: "1000" },
               { key: "Blade rotational speed (r/min)", value: "600" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "32500" },
               { key: "Total pressure (Pa)", value: "≤70" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "750" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1100" },
               { key: "Width (mm)", value: "1100" },
               { key: "Thickness (mm)", value: "400" },
            ],
         },
         {
            type: 'HYA-1220(44")',
            list: [
               { key: "Diameter blades (mm)", value: "1100" },
               { key: "Blade rotational speed (r/min)", value: "460" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "38000" },
               { key: "Total pressure (Pa)", value: "≤70" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "1100" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1200" },
               { key: "Width (mm)", value: "1200" },
               { key: "Thickness (mm)", value: "400" },
            ],
         },
         {
            type: 'HYA-1380(50")',
            list: [
               { key: "Diameter blades (mm)", value: "1250" },
               { key: "Blade rotational speed (r/min)", value: "439" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "44000" },
               { key: "Total pressure (Pa)", value: "≤70" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "1100" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1380" },
               { key: "Width (mm)", value: "1380" },
               { key: "Thickness (mm)", value: "400" },
            ],
         },
         {
            type: 'HYA-1530(56")',
            list: [
               { key: "Diameter blades (mm)", value: "1400" },
               { key: "Blade rotational speed (r/min)", value: "325" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "55800" },
               { key: "Total pressure (Pa)", value: "≤70" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "1500" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1530" },
               { key: "Width (mm)", value: "1530" },
               { key: "Thickness (mm)", value: "400" },
            ],
         },
      ],
   },
   {
      id: "hy-cow-house-hanging-exhaust-fan",
      name: "HY COW HOUSE HANGING EXHAUST FAN",
      heroImage: "",
      images: [
         "/product-images/hy-cow-house-hanging-exhaust-fan/image-1.webp",
         "/product-images/hy-cow-house-hanging-exhaust-fan/image-2.webp",
         "/product-images/hy-cow-house-hanging-exhaust-fan/image-3.webp",
      ],
      tags: [],
      category: "neagtive-pressure-fan",
      specifications: [
         {
            type: 'HYNF-800(29")',
            list: [
               { key: "Diameter blades (mm)", value: "710" },
               { key: "Blade rotational speed (r/min)", value: "660" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "22000" },
               { key: "Total pressure (Pa)", value: "60" },
               { key: "Noise decibels", value: "≤60" },
               { key: "Input power (W)", value: "370" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "800" },
               { key: "Width (mm)", value: "800" },
               { key: "Thickness (mm)", value: "420" },
            ],
         },
         {
            type: 'HYNF-900(30")',
            list: [
               { key: "Diameter blades (mm)", value: "750" },
               { key: "Blade rotational speed (r/min)", value: "630" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "28000" },
               { key: "Total pressure (Pa)", value: "65" },
               { key: "Noise decibels", value: "≤65" },
               { key: "Input power (W)", value: "550" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "900" },
               { key: "Width (mm)", value: "900" },
               { key: "Thickness (mm)", value: "420" },
            ],
         },
         {
            type: 'HYNF-1000(30")',
            list: [
               { key: "Diameter blades (mm)", value: "900" },
               { key: "Blade rotational speed (r/min)", value: "610" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "30000" },
               { key: "Total pressure (Pa)", value: "70" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "750" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1000" },
               { key: "Width (mm)", value: "1000" },
               { key: "Thickness (mm)", value: "420" },
            ],
         },
         {
            type: 'HYNF-1100(40")',
            list: [
               { key: "Diameter blades (mm)", value: "1000" },
               { key: "Blade rotational speed (r/min)", value: "600" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "32500" },
               { key: "Total pressure (Pa)", value: "70" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "750" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1100" },
               { key: "Width (mm)", value: "1100" },
               { key: "Thickness (mm)", value: "420" },
            ],
         },
         {
            type: 'HYNF-1220(44")',
            list: [
               { key: "Diameter blades (mm)", value: "1100" },
               { key: "Blade rotational speed (r/min)", value: "460" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "38000" },
               { key: "Total pressure (Pa)", value: "73" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "1100" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1220" },
               { key: "Width (mm)", value: "1200" },
               { key: "Thickness (mm)", value: "420" },
            ],
         },
         {
            type: 'HYNF-1380(50")',
            list: [
               { key: "Diameter blades (mm)", value: "1250" },
               { key: "Blade rotational speed (r/min)", value: "439" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "44000" },
               { key: "Total pressure (Pa)", value: "56" },
               { key: "Noise decibels", value: "≤75" },
               { key: "Input power (W)", value: "1100" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1380" },
               { key: "Width (mm)", value: "1380" },
               { key: "Thickness (mm)", value: "420" },
            ],
         },
         {
            type: 'HYNF-1530(56")',
            list: [
               { key: "Diameter blades (mm)", value: "1400" },
               { key: "Blade rotational speed (r/min)", value: "325" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "55800" },
               { key: "Total pressure (Pa)", value: "60" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "1500" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1530" },
               { key: "Width (mm)", value: "1530" },
               { key: "Thickness (mm)", value: "420" },
            ],
         },
      ],
   },
   {
      id: "hy-frp-cone-fan",
      name: "HY-FRP CONE FAN",
      heroImage: "",
      images: [
         "/product-images/hy-frp-cone-fan/image-1.webp",
         "/product-images/hy-frp-cone-fan/image-2.webp",
      ],
      tags: [],
      category: "neagtive-pressure-fan",
      specifications: [
         {
            type: "HYB-1630",
            list: [
               { key: "Size", value: "55 inch" },
               { key: "Propeller Dia (MM)", value: "1397" },
               { key: "Blade", value: "3 nylon blades" },
               { key: "Rated Speed", value: "710" },
               { key: "Air Capacity M³/h", value: "57000" },
               { key: "Rated Power", value: "1.5" },
               { key: "Voltage Frequency/Phase", value: "380V/220V" },
               { key: "Drive Mode", value: "Direct" },
               { key: "Complete Size DXHXW(mm)", value: "1530*1530*1480" },
               { key: "Size With Cone (mm)", value: "1540*1540" },
            ],
         },
         {
            type: "HYB-1530",
            list: [
               { key: "Size", value: "51 inch" },
               { key: "Propeller Dia (MM)", value: "1290" },
               { key: "Blade", value: "3 nylon blades" },
               { key: "Rated Speed", value: "710" },
               { key: "Air Capacity M³/h", value: "48000" },
               { key: "Rated Power", value: "1.1" },
               { key: "Voltage Frequency/Phase", value: "380V/220V" },
               { key: "Drive Mode", value: "Direct" },
               { key: "Complete Size DXHXW(mm)", value: "1530*1530*1220" },
               { key: "Size With Cone (mm)", value: "1460*1460" },
            ],
         },
         {
            type: "HYB-1560",
            list: [
               { key: "Size", value: "50 inch" },
               { key: "Propeller Dia (MM)", value: "1250" },
               { key: "Blade", value: "3 nylon blades" },
               { key: "Rated Speed", value: "710" },
               { key: "Air Capacity M³/h", value: "44000" },
               { key: "Rated Power", value: "1.1" },
               { key: "Voltage Frequency/Phase", value: "380V/220V" },
               { key: "Drive Mode", value: "Direct" },
               { key: "Complete Size DXHXW(mm)", value: "1460*1460*1220" },
               { key: "Size With Cone (mm)", value: "1400*1400" },
            ],
         },
         {
            type: "HYB-1170",
            list: [
               { key: "Size", value: "36 inch" },
               { key: "Propeller Dia (MM)", value: "915" },
               { key: "Blade", value: "3 nylon blades" },
               { key: "Rated Speed", value: "910" },
               { key: "Air Capacity M³/h", value: "25000" },
               { key: "Rated Power", value: "0.75" },
               { key: "Voltage Frequency/Phase", value: "380V/220V" },
               { key: "Drive Mode", value: "Direct" },
               { key: "Complete Size DXHXW(mm)", value: "2170*1170*1200" },
               { key: "Size With Cone (mm)", value: "1080*1080" },
            ],
         },
         {
            type: "HYB-850",
            list: [
               { key: "Size", value: "24 inch" },
               { key: "Propeller Dia (MM)", value: "610" },
               { key: "Blade", value: "6 nylon blades" },
               { key: "Rated Speed", value: "910" },
               { key: "Air Capacity M³/h", value: "12000" },
               { key: "Rated Power", value: "0.37" },
               { key: "Voltage Frequency/Phase", value: "380V/220V" },
               { key: "Drive Mode", value: "Direct" },
               { key: "Complete Size DXHXW(mm)", value: "810*810*1000" },
               { key: "Size With Cone (mm)", value: "740*740" },
            ],
         },
         {
            type: "HYB-660",
            list: [
               { key: "Size", value: "18 inch" },
               { key: "Propeller Dia (MM)", value: "460" },
               { key: "Blade", value: "8 nylon blades" },
               { key: "Rated Speed", value: "1400" },
               { key: "Air Capacity M³/h", value: "7400" },
               { key: "Rated Power", value: "0.37" },
               { key: "Voltage Frequency/Phase", value: "380V/220V" },
               { key: "Drive Mode", value: "Direct" },
               { key: "Complete Size DXHXW(mm)", value: "660*660*780" },
               { key: "Size With Cone (mm)", value: "580*580" },
            ],
         },
      ],
   },
   {
      id: "hy-butterfly-cone-fan",
      name: "HY-BUTTERFLY CONE FAN",
      heroImage: "",
      images: [
         "/product-images/hy-butterfly-cone-fan/image-1.webp",
         "/product-images/hy-butterfly-cone-fan/image-2.webp",
         "/product-images/hy-butterfly-cone-fan/image-3.webp",
      ],
      tags: [],
      category: "neagtive-pressure-fan",
      specifications: [
         {
            type: "HY-1000",
            list: [
               { key: "Diameter blades (mm)", value: "910" },
               { key: "Blade rotational speed (r/min)", value: "600" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "22000" },
               { key: "Total pressure (Pa)", value: "70" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "550" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1000" },
               { key: "Width (mm)", value: "1100" },
               { key: "Thickness (mm)", value: "1180" },
            ],
         },
         {
            type: "HY-1380",
            list: [
               { key: "Diameter blades (mm)", value: "1270" },
               { key: "Blade rotational speed (r/min)", value: "439" },
               { key: "Motor rotational speed (r/min)", value: "1400" },
               { key: "Air flow (m³/h)", value: "42500" },
               { key: "Total pressure (Pa)", value: "80" },
               { key: "Noise decibels", value: "≤70" },
               { key: "Input power (W)", value: "1100" },
               { key: "Rated voltage (V)", value: "380" },
               { key: "Height (mm)", value: "1380" },
               { key: "Width (mm)", value: "1380" },
               { key: "Thickness (mm)", value: "1300" },
            ],
         },
      ],
   },
   {
      id: "hy-air-cooler",
      name: "HY AIR COOLER",
      heroImage: "",
      images: [
         "/product-images/hy-air-cooler/image-1.webp",
         "/product-images/hy-air-cooler/image-2.webp",
         "/product-images/hy-air-cooler/image-3.webp",
      ],
      tags: [],
      category: "neagtive-pressure-fan",
      specifications: [
         {
            type: "HY-1.1",
            list: [
               { key: "Power kw", value: "1.1" },
               { key: "Voltage v", value: "380/220" },
               { key: "Air flow m³/h", value: "18000" },
               { key: "Applicable area m²", value: "100~150" },
               { key: "Size mm", value: "1100x1100x980" },
            ],
         },
         {
            type: "HY-1.5",
            list: [
               { key: "Power kw", value: "1.5" },
               { key: "Voltage v", value: "380/220" },
               { key: "Air flow m³/h", value: "20000" },
               { key: "Applicable area m²", value: "100~150" },
               { key: "Size mm", value: "1100x1100x980" },
            ],
         },
         {
            type: "HY-2.2",
            list: [
               { key: "Power kw", value: "2.2" },
               { key: "Voltage v", value: "380" },
               { key: "Air flow m³/h", value: "25000" },
               { key: "Applicable area m²", value: "200~350" },
               { key: "Size mm", value: "1140x1140x1150" },
            ],
         },
         {
            type: "HY-3.0",
            list: [
               { key: "Power kw", value: "3.0" },
               { key: "Voltage v", value: "380" },
               { key: "Air flow m³/h", value: "30000" },
               { key: "Applicable area m²", value: "200~350" },
               { key: "Size mm", value: "1280x1280x1200" },
            ],
         },
         {
            type: "HY-4.0",
            list: [
               { key: "Power kw", value: "4.0" },
               { key: "Voltage v", value: "380" },
               { key: "Air flow m³/h", value: "40000" },
               { key: "Applicable area m²", value: "200~350" },
               { key: "Size mm", value: "1400x1400x1400" },
            ],
         },
      ],
   },
   {
      id: "hy-cooling-pad",
      name: "HY COOLING PAD",
      heroImage: "/product-images/hy-cooling-pad/hero.png",
      images: ["/product-images/hy-cooling-pad/image-1.webp"],
      tags: ["featured", "hero"],
      category: "cooling-pad",
      specifications: [],
   },
   {
      id: "hy-plastic-cooling-pad",
      name: "HY-PLASTIC COOLING PAD",
      heroImage: "",
      images: ["/product-images/hy-plastic-cooling-pad/image-1.webp"],
      tags: [],
      category: "cooling-pad",
      specifications: [
         {
            type: null,
            list: [
               { key: "Ammonia removal rate", value: ">70%~95%" },
               { key: "Odor removal rate", value: ">40%~75%" },
               { key: "Dust removal rate", value: ">45%~80%" },
            ],
         },
      ],
   },
   {
      id: "hy-silos",
      name: "HY SILOS",
      heroImage: "/product-images/hy-silos/hero.webp",
      images: ["/product-images/hy-silos/image-1.webp"],
      tags: ["featured", "hero"],
      category: "farming-equipment",
      specifications: [
         {
            type: "HY1801 3.0",
            list: [
               { key: "Diameter", value: "1.8m" },
               { key: "Height", value: "3.06 meters" },
               { key: "Layers", value: "1" },
               { key: "Capacity", value: "4.62 cubic meters" },
               {
                  key: "Details",
                  value: "4 columns, 4 straight supports, 8 tension supports",
               },
            ],
         },
         {
            type: "HY1802 4.5",
            list: [
               { key: "Diameter", value: "1.8m" },
               { key: "Height", value: "3.06 meters" },
               { key: "Layers", value: "2" },
               { key: "Capacity", value: "6.92 cubic meters" },
               {
                  key: "Details",
                  value: "4 columns, 4 straight supports, 8 tension supports",
               },
            ],
         },
         {
            type: "HY1803 6.0",
            list: [
               { key: "Diameter", value: "1.8m" },
               { key: "Height", value: "6.3 meters" },
               { key: "Layers", value: "3" },
               { key: "Capacity", value: "9.23 cubic meters" },
               {
                  key: "Details",
                  value: "4 columns, 4 straight supports, 8 tension supports",
               },
            ],
         },
         {
            type: "HY2801 7",
            list: [
               { key: "Diameter", value: "2.8m" },
               { key: "Height", value: "4.5 meters" },
               { key: "Layers", value: "1" },
               { key: "Capacity", value: "10.77 cubic meters" },
               {
                  key: "Details",
                  value: "6 columns, 6 straight supports, 12 tension supports",
               },
            ],
         },
         {
            type: "HY2802 10.0",
            list: [
               { key: "Diameter", value: "2.8m" },
               { key: "Height", value: "5.4 meters" },
               { key: "Layers", value: "2" },
               { key: "Capacity", value: "15.38 cubic meters" },
               {
                  key: "Details",
                  value: "6 columns, 6 straight supports, 12 tension supports",
               },
            ],
         },
         {
            type: "HY2803 15",
            list: [
               { key: "Diameter", value: "2.8m" },
               { key: "Height", value: "6.3 meters" },
               { key: "Layers", value: "3" },
               { key: "Capacity", value: "23.08 cubic meters" },
               {
                  key: "Details",
                  value: "6 columns, 6 straight supports, 12 tension supports",
               },
            ],
         },
         {
            type: "HY2804 18",
            list: [
               { key: "Diameter", value: "2.8m" },
               { key: "Height", value: "7.2 meters" },
               { key: "Layers", value: "4" },
               { key: "Capacity", value: "27.69 cubic meters" },
               {
                  key: "Details",
                  value: "6 columns, 6 straight supports, 12 tension supports",
               },
            ],
         },
         {
            type: "HY3602 20",
            list: [
               { key: "Diameter", value: "3.6m" },
               { key: "Height", value: "5.4 meters" },
               { key: "Layers", value: "2" },
               { key: "Capacity", value: "30.76 cubic meters" },
               {
                  key: "Details",
                  value: "8 columns, 8 straight supports, 16 tension supports, 12 reinforcing ribs",
               },
            ],
         },
         {
            type: "HY3603 25",
            list: [
               { key: "Diameter", value: "3.6m" },
               { key: "Height", value: "6.3 meters" },
               { key: "Layers", value: "3" },
               { key: "Capacity", value: "38.46 cubic meters" },
               {
                  key: "Details",
                  value: "8 columns, 8 straight supports, 16 tension supports, 12 reinforcing ribs",
               },
            ],
         },
         {
            type: "HY3604 30",
            list: [
               { key: "Diameter", value: "3.6m" },
               { key: "Height", value: "7.2 meters" },
               { key: "Layers", value: "4" },
               { key: "Capacity", value: "46.15 cubic meters" },
               {
                  key: "Details",
                  value: "8 columns, 8 straight supports, 16 tension supports, 12 reinforcing ribs",
               },
            ],
         },
      ],
   },
   {
      id: "hy-poultry-light-filter",
      name: "HY-POULTRY LIGHT FILTER",
      heroImage: "",
      images: ["/product-images/hy-poultry-light-filter/image-1.webp"],
      tags: [],
      category: "farming-equipment",
      specifications: [],
   },
   {
      id: "hy-side-air-inlet",
      name: "HY-SIDE AIR INLET",
      heroImage: "",
      images: [
         "/product-images/hy-side-air-inlet/image-1.webp",
         "/product-images/hy-side-air-inlet/image-2.webp",
         "/product-images/hy-side-air-inlet/image-3.webp",
      ],
      tags: [],
      category: "farming-equipment",
      specifications: [],
   },
   {
      id: "hy-pig-feeding-line",
      name: "HY-PIG FEEDING LINE",
      heroImage: "",
      images: ["/product-images/hy-pig-feeding-line/image-1.webp"],
      tags: [],
      category: "farming-equipment",
      specifications: [],
   },
   {
      id: "hy-automatic-water-line",
      name: "HY-AUTOMATIC WATER LINE",
      heroImage: "",
      images: [
         "/product-images/hy-automatic-water-line/image-1.webp",
         "/product-images/hy-automatic-water-line/image-2.webp",
         "/product-images/hy-automatic-water-line/image-3.webp",
      ],
      tags: [],
      category: "farming-equipment",
      specifications: [],
   },
   {
      id: "hy-electric-heaters",
      name: "HY-ELECTRIC HEATERS",
      heroImage: "/product-images/hy-electric-heaters/hero.webp",
      images: [
         "/product-images/hy-electric-heaters/image-1.webp",
         "/product-images/hy-electric-heaters/image-2.jpg",
         "/product-images/hy-electric-heaters/image-3.jpg",
         "/product-images/hy-electric-heaters/image-4.jpg",
      ],
      tags: ["featured", "hero"],
      category: "heating-equipment",
      specifications: [
         {
            type: "HYD-5",
            list: [
               { key: "Power kW", value: "0.09" },
               { key: "Voltage V", value: "380/220" },
               { key: "Heating area m²", value: "50-80" },
               { key: "Dimensions mm", value: "450x580x710" },
            ],
         },
         {
            type: "HYD-10",
            list: [
               { key: "Power kW", value: "0.12" },
               { key: "Voltage V", value: "380/220" },
               { key: "Heating area m²", value: "100-130" },
               { key: "Dimensions mm", value: "500x650x780" },
            ],
         },
         {
            type: "HYD-15",
            list: [
               { key: "Power kW", value: "0.37" },
               { key: "Voltage V", value: "380/220" },
               { key: "Heating area m²", value: "130-180" },
               { key: "Dimensions mm", value: "580x680x840" },
            ],
         },
         {
            type: "HYD-20",
            list: [
               { key: "Power kW", value: "0.37" },
               { key: "Voltage V", value: "380/220" },
               { key: "Heating area m²", value: "180-230" },
               { key: "Dimensions mm", value: "580x680x840" },
            ],
         },
         {
            type: "HYD-30",
            list: [
               { key: "Power kW", value: "0.55" },
               { key: "Voltage V", value: "380/220" },
               { key: "Heating area m²", value: "230-350" },
               { key: "Dimensions mm", value: "680x770x1020" },
            ],
         },
         {
            type: "HYD-40",
            list: [
               { key: "Power kW", value: "1.5" },
               { key: "Voltage V", value: "380/220" },
               { key: "Heating area m²", value: "350-450" },
               { key: "Dimensions mm", value: "680x710x1180" },
            ],
         },
         {
            type: "HYD-50",
            list: [
               { key: "Power kW", value: "1.5" },
               { key: "Voltage V", value: "380/220" },
               { key: "Heating area m²", value: "450-500" },
               { key: "Dimensions mm", value: "680x710x1180" },
            ],
         },
      ],
   },
   {
      id: "hy-series-coal-burning-heater",
      name: "HY-SERIES COAL-BURNING HEATER",
      heroImage: "",
      images: ["/product-images/hy-series-coal-burning-heater/image-1.webp"],
      tags: [],
      category: "heating-equipment",
      specifications: [
         {
            type: "HYMR-5",
            list: [
               { key: "Heat output (kcal/h)", value: "50000" },
               { key: "Hot air temperature (°C)", value: "80–150" },
               { key: "Heating volume (m³/h)", value: "9500" },
               { key: "Consumer of fuel (kg/h)", value: "5–10" },
               { key: "Power (kw)", value: "1.87" },
               { key: "Outer Size (mm)", value: "1250*800*1850" },
               { key: "Weight (kg)", value: "750" },
               { key: "Heating area (m³)", value: "300" },
            ],
         },
         {
            type: "HYMR-10",
            list: [
               { key: "Heat output (kcal/h)", value: "100000" },
               { key: "Hot air temperature (°C)", value: "80–150" },
               { key: "Heating volume (m³/h)", value: "18700" },
               { key: "Consumer of fuel (kg/h)", value: "10–20" },
               { key: "Power (kw)", value: "3.55" },
               { key: "Outer Size (mm)", value: "2030*950*2040" },
               { key: "Weight (kg)", value: "1150" },
               { key: "Heating area (m³)", value: "600" },
            ],
         },
         {
            type: "HYMR-20",
            list: [
               { key: "Heat output (kcal/h)", value: "200000" },
               { key: "Hot air temperature (°C)", value: "80–150" },
               { key: "Heating volume (m³/h)", value: "37400" },
               { key: "Consumer of fuel (kg/h)", value: "30–40" },
               { key: "Power (kw)", value: "5.15" },
               { key: "Outer Size (mm)", value: "2450*1250*2280" },
               { key: "Weight (kg)", value: "1700" },
               { key: "Heating area (m³)", value: "1200" },
            ],
         },
         {
            type: "HYMR-30",
            list: [
               { key: "Heat output (kcal/h)", value: "300000" },
               { key: "Hot air temperature (°C)", value: "80–150" },
               { key: "Heating volume (m³/h)", value: "39400" },
               { key: "Consumer of fuel (kg/h)", value: "40–50" },
               { key: "Power (kw)", value: "6.75" },
               { key: "Outer Size (mm)", value: "2720*1250*2600" },
               { key: "Weight (kg)", value: "2400" },
               { key: "Heating area (m³)", value: "1800" },
            ],
         },
         {
            type: "HYMR-40",
            list: [
               { key: "Heat output (kcal/h)", value: "400000" },
               { key: "Hot air temperature (°C)", value: "80–150" },
               { key: "Heating volume (m³/h)", value: "42500" },
               { key: "Consumer of fuel (kg/h)", value: "50–60" },
               { key: "Power (kw)", value: "9.1" },
               { key: "Outer Size (mm)", value: "2920*1300*2600" },
               { key: "Weight (kg)", value: "2600" },
               { key: "Heating area (m³)", value: "2400" },
            ],
         },
      ],
   },
   {
      id: "hy-series-light-oil-burning-heater",
      name: "HY-SERIES LIGHT OIL BURNING HEATER",
      heroImage: "",
      images: [
         "/product-images/hy-series-light-oil-burning-heater/image-1.webp",
         "/product-images/hy-series-light-oil-burning-heater/image-2.webp",
      ],
      tags: [],
      category: "heating-equipment",
      specifications: [
         {
            type: "HYRY-30",
            list: [
               { key: "Power", value: "30KW" },
               { key: "Voltage", value: "220V 50Hz" },
               { key: "Air flow m³/h", value: "720" },
               { key: "Fuel consumption L/h", value: "1.5~2.4" },
               { key: "Fuel tank capacity L", value: "38" },
               { key: "Usage space m²", value: "240" },
               { key: "Product size mm", value: "920x456x630" },
               { key: "Packaging size mm", value: "930x450x500" },
               { key: "Net weight kg", value: "21.5" },
               { key: "Gross weight kg", value: "23.5" },
            ],
         },
         {
            type: "HYRY-50",
            list: [
               { key: "Power", value: "50KW" },
               { key: "Voltage", value: "220V 50Hz" },
               { key: "Air flow m³/h", value: "1100" },
               { key: "Fuel consumption L/h", value: "2.0~4.0" },
               { key: "Fuel tank capacity L", value: "56" },
               { key: "Usage space m²", value: "400" },
               { key: "Product size mm", value: "1050x490x615" },
               { key: "Packaging size mm", value: "1080x5000x580" },
               { key: "Net weight kg", value: "27.4" },
               { key: "Gross weight kg", value: "33" },
            ],
         },
         {
            type: "HYRY-70",
            list: [
               { key: "Power", value: "70KW" },
               { key: "Voltage", value: "220V 50Hz" },
               { key: "Air flow m³/h", value: "1300" },
               { key: "Fuel consumption L/h", value: "2.5~5.4" },
               { key: "Fuel tank capacity L", value: "68" },
               { key: "Usage space m²", value: "450" },
               { key: "Product size mm", value: "1170x570x705" },
               { key: "Packaging size mm", value: "1215x580x705" },
               { key: "Net weight kg", value: "40.8" },
               { key: "Gross weight kg", value: "45.8" },
            ],
         },
         {
            type: "HYRY-100",
            list: [
               { key: "Power", value: "100KW" },
               { key: "Voltage", value: "220V 50Hz" },
               { key: "Air flow m³/h", value: "1500" },
               { key: "Fuel consumption L/h", value: "4.0~8.0" },
               { key: "Fuel tank capacity L", value: "69" },
               { key: "Usage space m²", value: "600" },
               { key: "Product size mm", value: "1195x570x690" },
               { key: "Packaging size mm", value: "1251x581x706" },
               { key: "Net weight kg", value: "45.8" },
               { key: "Gross weight kg", value: "53" },
            ],
         },
      ],
   },
   {
      id: "hy-water-and-wind-coal-burning-heating-machine",
      name: "HY-WATER AND WIND COAL BURNING HEATING MACHINE",
      heroImage: "",
      images: [
         "/product-images/hy-water-and-wind-coal-burning-heating-machine/image-1.webp",
         "/product-images/hy-water-and-wind-coal-burning-heating-machine/image-2.webp",
      ],
      tags: [],
      category: "heating-equipment",
      specifications: [
         {
            type: "HY-10",
            list: [
               { key: "Rated heat capacity Kcal/h", value: "100000" },
               { key: "Hot air outlet temperature ℃", value: "60~120" },
               { key: "Hot water outlet temperature ℃", value: "50~80" },
               { key: "Power KW", value: "3.67" },
               { key: "Voltage V", value: "380/220" },
               { key: "Dimension mm", value: "1500*1100*1600" },
               { key: "Weight kg", value: "1300" },
            ],
         },
         {
            type: "HY-20",
            list: [
               { key: "Rated heat capacity Kcal/h", value: "200000" },
               { key: "Hot air outlet temperature ℃", value: "60~120" },
               { key: "Hot water outlet temperature ℃", value: "50~80" },
               { key: "Power KW", value: "3.91" },
               { key: "Voltage V", value: "380/220" },
               { key: "Dimension mm", value: "1800*1200*1600" },
               { key: "Weight kg", value: "1800" },
            ],
         },
         {
            type: "HY-30",
            list: [
               { key: "Rated heat capacity Kcal/h", value: "300000" },
               { key: "Hot air outlet temperature ℃", value: "60~120" },
               { key: "Hot water outlet temperature ℃", value: "50~80" },
               { key: "Power KW", value: "5.3" },
               { key: "Voltage V", value: "380/220" },
               { key: "Dimension mm", value: "1900*1300*1700" },
               { key: "Weight kg", value: "2100" },
            ],
         },
         {
            type: "HY-40",
            list: [
               { key: "Rated heat capacity Kcal/h", value: "400000" },
               { key: "Hot air outlet temperature ℃", value: "60~120" },
               { key: "Hot water outlet temperature ℃", value: "50~80" },
               { key: "Power KW", value: "5.3" },
               { key: "Voltage V", value: "380/220" },
               { key: "Dimension mm", value: "2000*1400*1800" },
               { key: "Weight kg", value: "2400" },
            ],
         },
      ],
   },
   {
      id: "hy-dry-and-wet-seprator",
      name: "HY-DRY AND WET SEPARATOR",
      heroImage: "/product-images/hy-dry-and-wet-seprator/hero.webp",
      images: ["/product-images/hy-dry-and-wet-seprator/image-1.webp"],
      tags: ["featured", "hero"],
      category: "fecal-cleaning-equipment",
      specifications: [],
   },
   {
      id: "hy-fecal-pumping-pump",
      name: "HY-FECAL PUMPING PUMP",
      heroImage: "",
      images: ["/product-images/hy-fecal-pumping-pump/image-1.webp"],
      tags: [],
      category: "fecal-cleaning-equipment",
      specifications: [],
   },
   {
      id: "hy-conveyor-manure-cleaner",
      name: "HY-CONVEYOR MANURE CLEANER",
      heroImage: "",
      images: [
         "/product-images/hy-conveyor-manure-cleaner/image-1.webp",
         "/product-images/hy-conveyor-manure-cleaner/image-2.webp",
      ],
      tags: [],
      category: "fecal-cleaning-equipment",
      specifications: [],
   },
   {
      id: "hy-roof-ventilation-fan",
      name: "HY-ROOF VENTILATION FAN",
      heroImage: "/product-images/hy-roof-ventilation-fan/hero.webp",
      images: ["/product-images/hy-roof-ventilation-fan/image-1.webp"],
      tags: ["featured", "hero"],
      category: "other-fans",
      specifications: [
         {
            type: null,
            list: [
               { key: "Power", value: "0.25KW" },
               { key: "Gas displacement", value: "3500-4000m³" },
               { key: "Diameter", value: "600mm" },
               { key: "Height", value: "450mm" },
               { key: "Install diameter", value: "530mm" },
            ],
         },
      ],
   },
   {
      id: "hy-air-circulation-fan",
      name: "HY-AIR CIRCULATION FAN",
      heroImage: "",
      images: [
         "/product-images/hy-air-circulation-fan/image-1.webp",
         "/product-images/hy-air-circulation-fan/image-2.webp",
      ],
      tags: [],
      category: "other-fans",
      specifications: [
         {
            type: "HY-400",
            list: [
               { key: "Air flow (m³/h)", value: "3200" },
               { key: "Power (w)", value: "120" },
               { key: "Voltage (v)", value: "220/380" },
               { key: "Total pressure (Pa)", value: "60" },
               { key: "Frequency (Hz)", value: "50" },
               { key: "Effective distance (m)", value: "12-16" },
            ],
         },
         {
            type: "HY-500",
            list: [
               { key: "Air flow (m³/h)", value: "5400" },
               { key: "Power (w)", value: "180" },
               { key: "Voltage (v)", value: "220/380" },
               { key: "Total pressure (Pa)", value: "60" },
               { key: "Frequency (Hz)", value: "50" },
               { key: "Effective distance (m)", value: "18-22" },
            ],
         },
         {
            type: "HY-600",
            list: [
               { key: "Air flow (m³/h)", value: "6500" },
               { key: "Power (w)", value: "370" },
               { key: "Voltage (v)", value: "220/380" },
               { key: "Total pressure (Pa)", value: "60" },
               { key: "Frequency (Hz)", value: "50" },
               { key: "Effective distance (m)", value: "24-28" },
            ],
         },
      ],
   },
   {
      id: "hy-vertical-circulating-fan",
      name: "HY-VERTICAL CIRCULATING FAN",
      heroImage: "",
      images: ["/product-images/hy-vertical-circulating-fan/image-1.webp"],
      tags: [],
      category: "other-fans",
      specifications: [
         {
            type: "HY-500",
            list: [
               { key: "VOLTAGE", value: "220 V/50 Hz" },
               { key: "INPUT POWER", value: "210 W" },
               { key: "ELECTRICITY", value: "1.0 A" },
               { key: "RPM", value: "950 RPM" },
               { key: "VOLUME", value: "5000 m³/H" },
               { key: "NOISE(7m)", value: "50dB" },
               { key: "WEIGHT", value: "10.5KG" },
               { key: "VOLUME(mm)", value: "680x680x380" },
            ],
         },
      ],
   },
];
